### ISSUE TITLE
OVF upload to catalog fails

### ISSUE THREAD

**Issue by mgaruccio** [vmware/vcd-cli#249] opened 2018-10-04 20:34 UTC
When attempting to upload an OVF to a catalog the upload fails almost immediately with the error below.  The console then shows an in-progress import that remains stuck at 1% until it is manually cancelled. 

vcd version: 9.5.9851390
cli version: 21.0.0
python version: 3.6.6

vcd catalog upload -i ubuntu-16.04-server-cloudimg-amd64-k8s cse ubuntu-16.04-server-cloudimg-amd64.ova
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 617, in upload_ovf
    EntityType.TEXT_XML.value)
  File "/home/mike/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 990, in put_resource
    objectify_results=objectify_results)
  File "/home/mike/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 830, in _do_request
    response), _objectify_response(response, objectify_results))
  File "/home/mike/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 611, in _get_response_request_id
    return response.headers[self._REQUEST_ID_HDR_NAME]
  File "/home/mike/.local/lib/python3.6/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-vmware-vcloud-request-id'

Usage: vcd catalog upload [OPTIONS] <catalog-name> <file-name>
Try "vcd catalog upload -h" for help.

Error: Ovf upload failed

**Comment by rocknes** [comment] 2018-10-04 22:14
Hi,

Uploading a template involves multiple steps viz.
1. Create the catalog item
2. Upload the descriptor file
3. Wait for upload locations for vmdk files to show up in spool area
4. Upload data bits to those file locations
5. Wait for vCD to import the uploaded files into hosts.

From the point in failure, it seems that pyvcloud was trying to upload the ovf descriptor file (step 2) and that PUT call never succeeded. Will it be possible for you to 
1. logout of the current session using ``vcd logout``.
2. specify the flags ``-i`` and ``-w`` while logging back in using the command ``vcd login...``
3. retry the upload.
4. and if it fails this time, please grab and upload the file ``vcd.log`` here.

If the issue persists I think it will be worthwhile to run the underlying REST calls using postman to make sure that it's not vCD that is causing the issue.

**Comment by mgaruccio** [comment] 2018-10-05 12:59
I logged out, logged back in with -i and -w and attempted the upload again with the same error.  vcd.log is attached.  Working on stepping through the calls in PostMan now.
[vcd.log](https://github.com/vmware/vcd-cli/files/2450342/vcd.log)

**Comment by rocknes** [comment] 2018-10-05 19:20
This line was probably added by someone who created the ova file / authored the ovf file.
I think it's safe to get rid of the comment tag and proceed with the upload.

**Comment by mgaruccio** [comment] 2018-10-05 19:45
Ok I gave that a try and it failed again with the same error, I stepped through things in PostMan again and it looks like the problem wasn't actually the XML.  The first time I hit Send it fails but if I just send the exact same request again it works fine.  Tested that twice with the same result, failed both times the first time I tried to send and succeeded the second.  I'll be following up with VMWare to see if they can trace down where that issue lies.  Thank you for the assistance.

**Comment by medea61** [comment] 2018-10-08 19:41
I think I am seeing the same issue. 

it looks like the upload sends the first 2MB of the (first) vmdk and then fails. i tried multiple different ova files with the same result.

vCD: 9.5.0.10264774
vcd-cli version: 21.0.0
python version: 3.6.5

[vcd.log](https://github.com/vmware/vcd-cli/files/2457476/vcd.log)

**Comment by rocknes** [comment] 2018-10-08 19:58
``BrokenPipeError: [Errno 32] Broken pipe`` - vCD is hanging up on the connection.

vCD team is aware of this bug, and it's being tracked internally. I will get in touch with them and try to see if they can find out why vCD is closing the connection on clients.

**Comment by rocknes** [comment] 2018-10-08 20:04
Meanwhile I found something interesting in the vcd.log

2018-10-08 21:35:10,565 | DEBUG | pyvcloud.vcd.cl | client          | upload_fragm | Request headers: {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-vcloud-authorization': '3926e4c6e7574735918598393a18ccf4'}, {'Content-Range': 'bytes 1048576-1048575/284948480', 'Content-Length': '1048576'}

The header content range is sending -1/284948480 which is definitely wrong! I will take a look at this.

**Comment by mgaruccio** [comment] 2018-10-09 02:10
Just to confirm for everyone, I was originally seeing some different errors but I was on a beta build of 9.5, after updating to the new release bits I am seeing the `BrokenPipeError: [Errno 32] Broken pipe` error mentioned above.

**Comment by mgaruccio** [comment] 2018-10-09 18:31
Strange that your not seeing it on the GA build, I'm running the latest build and I just tried to upload a template via the console and I'm seeing similar connection reset issues there as well, although from the console it shows some amount of progress before failing. Which build number are you testing against?

email is mike.garuccio@expedient.com if you'd like to send over the updated pyvcloud files.

**Comment by rocknes** [comment] 2018-10-09 18:49
For testing, I am using :
vCD 9.5.0.10264774, 
python 3.6.5, 
pyvcloud 20.0.0, 
vcd-cli 21.0.0 and
ubuntu-16.04-server-cloudimg-amd64.ova

Sample run
------------
(vcd-cli) C:\code\vcd-cli>vcd catalog upload test-cat ubuntu-16.04-server-cloudimg-amd64.ova
upload 291,491,328 of 291,491,328 bytes, 100%
property    value
----------  --------------------------------------
file        ubuntu-16.04-server-cloudimg-amd64.ova
size        291502092

(vcd-cli) C:\code\vcd-cli>

I will mail you the whl file in a bit.

**Comment by medea61** [comment] 2018-10-09 19:40
strange. i have the exact same versions and see the error. feel free to send me an email and i will create you a test account.

**Comment by mgaruccio** [comment] 2018-10-09 20:07
I tried the updated pyvcloud files in CSE and I'm getting the same errors I was getting with the pre-release code a few days ago, namely 500 "error persisting client data".  

@medea61 are you by chance able to upload via the GUI?  I'm currently trying and it goes to 33% then sits for a while before failing.  While this is happening I'm seeing a number of `500 (Error persisting client data)` codes while uploading the ovf, which it appears to keep retrying until it is successful, followed by `net::ERR_CONNECTION_RESET` errors while attempting to transfer the VMDK.

**Comment by rocknes** [comment] 2018-10-09 20:18
Given the upload via UI is failing too I strongly suspect that the core problem is in vCD. If you see the broken pipe 32 error with the hacked pyvcloud let me know.

**Comment by medea61** [comment] 2018-10-09 20:19
@mgaruccio yes. uploads via the tenant portal work perfectly well for me. as far as i remember should the task in vCD stay at 1% up until the end of the upload. everything else is post-upload to the transfer store.

**Comment by mgaruccio** [comment] 2018-10-09 22:28
Ok, so we had another issue with vCD occurring at the same time that is now resolved.  Uploads via the console work and I now see the upload actually starting in vcd-cli and then failing at 1% (different number of bytes each time though).  

I attempted to apply your patch by removing pyvcloud and then running pip against the provided wheel file but still received the EPIPE errors below.  Not sure if I'm missing something I was supposed to do to perform the install (apologies, fairly new to python)

```
vcd catalog upload cse ubuntu-16.04-server-cloudimg-amd64.ova
upload 4,194,304 of 284,948,480 bytes, 1%Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 308, in _send_until_done
    return self.connection.send(data)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1632, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1540, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (32, 'EPIPE')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 319, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 314, in _send_until_done
    raise SocketError(str(e))
OSError: (32, 'EPIPE')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 319, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/home/mike/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 314, in _send_until_done
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(32, 'EPIPE')",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 649, in upload_ovf
    callback=callback)
  File "/home/mike/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 716, in _upload_file
    file_name, target_uri, chunk_size=chunk_size, callback=callback)
  File "/home/mike/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 793, in _upload_part_file
    self.client.upload_fragment(target_uri, data, range_str)
  File "/home/mike/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 936, in upload_fragment
    verify=self._verify_ssl_certs)
  File "/home/mike/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mike/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/mike/.local/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(32, 'EPIPE')",))

Usage: vcd catalog upload [OPTIONS] <catalog-name> <file-name>
Try "vcd catalog upload -h" for help.

Error: Ovf upload failed
```

**Comment by rocknes** [comment] 2018-10-10 00:34
From the attached log I see ``4,194,304 of 284,948,480 bytes`` which means 4 PUT calls (1024 * 1024 bytes are transferred in one call) were successful and the 5th one failed. The fix in the hacked pyvcloud is working, otherwise the 2nd call should have failed. Did you try to upload the template using flex UI?

No, you don't need to do anything apart from pip install ..pyvcloud.whl
I still believe that the issue is in vCD (probably config/network related). Can you look at vCD logs to see why vCD is closing the connection?

On a separate note, I don't think the upload getting aborted at 1% is important. All it means is that the upload fails early on (first few PUT calls). The % raises as more and more PUT calls succeed.

**Comment by mgaruccio** [comment] 2018-10-10 14:42
I tried running the upload from a server on the same network segment(after applying the pyvcloud patch) and I'm still seeing the issue so I don't think the problem is network related, and I was able to successfully upload templates using the HTML5 UI.

After reviewing the VCD logs I'm only seeing one warning message appearing in any of them at the time of the upload but it looks like it is happening after the upload crashes, that message is below.

```
2018-10-10 10:16:23,168 | WARN     | task-service-activity-pool-3 | VAppManagerImpl                | vApp ubuntu-16.04-server-cloudimg-amd64.ova does not have any folder | requestId=e3b8e265-d415-45f1-bcab-ec0be694b88f,request=POST https://vcd-rc.expedient.com/api/catalog/b1f7ee3c-5b05-4ad1-a781-30ce33259cb6/action/upload,requestTime=1539180898691,remoteAddress=10.181.185.149:21145,userAgent=python-requests/2.19.1,accept=application/*+xml;version 31.0 vcd=03ffeecb-3f4f-4da9-94ec-38d0fafa10cd,task=f1aa18df-4a43-46d3-a69e-fbdc82da4f77 activity=(com.vmware.vcloud.backendbase.management.system.TaskActivity,urn:uuid:f1aa18df-4a43-46d3-a69e-fbdc82da4f77) vcd=03ffeecb-3f4f-4da9-94ec-38d0fafa10cd,task=c4a8336e-9881-4fd7-b1ce-524b4c141adb activity=(com.vmware.vcloud.backendbase.management.system.TaskActivity,urn:uuid:c4a8336e-9881-4fd7-b1ce-524b4c141adb)
```

I also noticed that every attempt since the log I uploaded yesterday is crashing at 3,145,728 bytes, at the same time the debug log on VCD only shows the first two chunks as received, then without logging any warnings or errors the logs being to show it waiting for the upload to complete but not receiving any data.  Uploading my vcd.log so you can see the output I'm seeing on my end and can provide logs from the vcd cells themselves if you need any of them.

**Comment by rocknes** [comment] 2018-10-10 20:28
The latest vcd.log has the following in the upload requests to vCD
'Content-Range': 'bytes 1048576-*1048575*/284948480
which means that the fixed pyvcloud whl file I mailed you yesterday is not being used.

Can you please navigate to 
(windows) ~\Envs\<virtual env name>\Lib\site-packages\pyvcloud\vcd\
(mac/linux) ~/.virtualenvs/<virtual env name>/Lib/site-pacakges/pyvcloud/vcd/

And edit org.py line 789 from
``range_str = 'bytes %s-%s/%s' % \
                                (offset + uploaded_bytes,
                                 data_size - 1,
                                 total_file_size)``
to
``range_str = 'bytes %s-%s/%s' % \
                                (offset + uploaded_bytes,
                                 offset + uploaded_bytes + data_size - 1,
                                 total_file_size)
``

And then rerun the command to upload the template.

**Comment by mgaruccio** [comment] 2018-10-10 22:35
Swapped that line and tried again getting the same error.  Not sure how far back that last log went so I backed it up and created a clean one showing the error. 
[vcd.log](https://github.com/vmware/vcd-cli/files/2466724/vcd.log)

**Comment by rocknes** [comment] 2018-10-10 23:52
Ok, found something of interest in your log.
With every request that vcd-cli (pyvcloud) is making we are sending a header ``'Connection': 'keep-alive'``, which basically is a way to ask vCD to keep the TCP connection alive, we will be pumping more data on this channel. However your vCD server is ignoring that and sending us ``'Connection': 'close'`` in the Response headers. And this is the root cause behind the failures we are seeing.  We are writing to a closed socket, which raises broken pipe Error 32.

My hypothesis was that since we wrote at the wrong range, vCD was closing the socket. But with the fix in, that's not the case anymore. I believe the server is configured to close all connections after it sends out the response..

Do you have a load balancer in front of the vCD server? Load balancers typically closes out the connection immediately.

**Comment by mgaruccio** [comment] 2018-10-11 14:27
Ah yea that solves it.  I'd tried bypassing the load balancer earlier but not since patching the module, just tried again and I'm able to get a template uploaded.  Thank you for all the assistance with this problem.

**Comment by rocknes** [comment] 2018-10-11 19:07
Cool :)

**Closed** 2018-10-11 19:07 UTC
